FROM docker.dragonflydb.io/dragonflydb/dragonfly
  
RUN apt update
RUN apt install -y \
        net-tools \
        iputils-ping \
        bash \
        tcpdump \
        iperf \
        busybox \
        iproute2

CMD /bin/bash