{
 "title": "TIP - Dashboards",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dragonfly_memory_used_bytes{}" }
   ]
  },
  {
   "title": "Comitted memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dragonfly_comitted_memory{}" }
   ]
  },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dragonfly_connected_clients{}" }
   ]
  },
  {
   "title": "Commands processed in last 10 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(dragonfly_commands_processed_total{}[10s])"
    }
   ]
  }
 ]
}